Use Netty Epoll
infinispan/infinispan-quarkus pull request #103
Opened 2022-07-29 10:27 UTC by ryanemerson

2022-08-10 20:50 UTC, wburns requested changes

2022-08-10 20:50 UTC, wburns commented on server/deployment/src/main/java/org/infinispan/quarkus/server/deployment/InfinispanServerProcessor.java
> +            "META-INF/native/libnetty_transport_native_epoll_x86_64.so",
I am guessing we only want to add this when linux is available.

2022-08-10 20:50 UTC, wburns commented on server/runtime/src/main/java/org/infinispan/quarkus/server/runtime/graal/SubstituteNettyClasses.java
> +      Class<? extends ServerChannel> channel = EpollServerSocketChannel.class;
Can we use Epoll always? Maybe we can remove this class now so it will pick based on the available classes?

2022-08-10 20:50 UTC, wburns commented on server/runtime/pom.xml
> +            <artifactId>netty-transport-native-epoll</artifactId>
Will this work in Windows?

2022-08-11 14:50 UTC, ryanemerson commented on server/runtime/pom.xml
> +            <artifactId>netty-transport-native-epoll</artifactId>
No idea ... does the current native server work in windows?

We need native CLI for windows, but server seems overkill to me.

2024-08-13 08:40 UTC, closed without merging